<a href="https://colab.research.google.com/github/hws2002/Deep_Learning_with_Keras/blob/main/Chapter12/BinaryCrossentropy_binary_crossentropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import keras

In [6]:
import numpy as np
img = np.ones((1,4,4,1))
img[0]

y_true = np.array(
    [
        [[[1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [1.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.]]],
        [[[1.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [1.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [1.]]]
    ]
)
y_true.shape

(2, 4, 4, 1)

In [7]:
y_pred = np.random.uniform( 0.,1., (2,4,4,1))
# y_pred = np.random.randn(1,4,4,1)
y_pred

array([[[[0.91898888],
         [0.94655193],
         [0.40438366],
         [0.60319126]],

        [[0.47290383],
         [0.83940743],
         [0.3734726 ],
         [0.09686357]],

        [[0.18343606],
         [0.25997016],
         [0.5435703 ],
         [0.55898521]],

        [[0.55417768],
         [0.64225547],
         [0.34639724],
         [0.1133084 ]]],


       [[[0.66085685],
         [0.85196787],
         [0.24393725],
         [0.90326796]],

        [[0.76672183],
         [0.79900228],
         [0.09894521],
         [0.54235994]],

        [[0.14876183],
         [0.60180765],
         [0.2669363 ],
         [0.56619736]],

        [[0.27322482],
         [0.65096448],
         [0.32396262],
         [0.04711204]]]])

In [13]:
bce = keras.losses.BinaryCrossentropy()
bce(y_true,y_pred).numpy()

0.8679227

In [8]:
bce = keras.losses.BinaryCrossentropy(axis = (1,2), reduction = None)
bce(y_true,y_pred).numpy()

array([[0.7632199],
       [0.9726257]], dtype=float32)

In [9]:
bce = keras.losses.BinaryCrossentropy(axis = (1,2), reduction = 'sum')
bce(y_true,y_pred).numpy()

1.7358456

In [11]:
bce = keras.losses.BinaryCrossentropy(axis = (1,2), reduction = 'sum_over_batch_size')
bce(y_true,y_pred).numpy()

0.8679228

In [12]:
import tensorflow as tf
tf.reduce_mean(tf.reduce_sum(keras.losses.binary_crossentropy(y_true, y_pred), axis = (1,2)))

<tf.Tensor: shape=(), dtype=float64, numpy=13.886763559501397>