<a href="https://colab.research.google.com/github/hws2002/Deep_Learning_with_Keras/blob/main/Chapter12/KLD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def entropy(prob):
  return -np.sum(prob * np.log(prob))

In [ ]:
import tensorflow as tf

def entropy_tf(prob):
  return -tf.reduce_sum(prob * tf.math.log(prob))

In [ ]:
p = tf.random.uniform((6,), 1,6, )
p /= tf.reduce_sum(p)
p

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.11061365, 0.1633855 , 0.33320987, 0.1949844 , 0.10434715,
       0.09345939], dtype=float32)>

In [ ]:
entropy(p)

1.6818429

In [ ]:
entropy_tf(p)

<tf.Tensor: shape=(), dtype=float32, numpy=1.6818428>

In [ ]:
def crossentropy_tf(p,q):
  return -tf.reduce_sum(p * tf.math.log(q))

In [ ]:
def kld(p,q):
  return crossentropy_tf(p,q) - entropy(p)

In [ ]:
original_p = tf.constant([1/6, 1/6, 1/6, 1/6, 1/6, 1/6], dtype = tf.float32)
original_p

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667], dtype=float32)>

In [ ]:
# 최대 엔트로피를 갖는 균등 분포
entropy_tf(original_p)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7917597>

In [ ]:
eps = 1e-10
q = tf.constant([eps,eps,eps,eps,eps, 1 - 5*eps], dtype = tf.float32)

In [ ]:
kld(original_p,q)

<tf.Tensor: shape=(), dtype=float32, numpy=17.39645>

In [ ]:
q_same = original_p
kld(original_p, q_same)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
q_sim = tf.Variable(original_p)
q_sim[0].assign(q_sim[0] + 0.1)
q_sim[1].assign(q_sim[1] - 0.1)
q_sim

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=
array([0.26666668, 0.06666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667], dtype=float32)>

In [ ]:
kld(original_p, q_sim)

<tf.Tensor: shape=(), dtype=float32, numpy=0.07438111>